#Makefile to Compile OpenCV Code in C++ on Ubuntu/Linux
GCC = g++
VER = -std=c++0x
GGDB = -ggdb
CFLAGS = `pkg-config --cflags opencv`
LIBS = `pkg-config --libs opencv` -ltbb -pthread
BASE = `basename
EXT = .cpp`

% : %
	$(GCC) $(VER) $(GGDB) $(CFLAGS) -o $(BASE) $@.cpp $(EXT) $@.cpp $(LIBS) 
